name: Backend CI-CD

on:
  push:
    branches: [main,dev]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test || echo "No tests yet"

  deploy-dev:
    needs: build-test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: curl -X POST ${{ secrets.RENDER_BACKEND_DEV_HOOK }}

  deploy-beta:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - run: curl -X POST ${{ secrets.RENDER_BACKEND_BETA_HOOK }}

  deploy-prod:
    needs: deploy-beta
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: curl -X POST ${{ secrets.RENDER_BACKEND_PROD_HOOK }}
